#!/usr/bin/env bash

set -e

cd ./metrics

rm -rf .cdt
cdt2 package install --autofill

echo "-------------------------------------------"
echo "Linking to libraries and child applications"
echo "$childApp"
for childApp in ../*; do
    if [ "$childApp" == "../metrics" ] || [ "$childApp" == "../script" ]; then
       continue
    fi

    cdt2 package link ${childApp}
done

echo "-----------------------"
echo "Linking to the tablelib"

cdt2 package link ./
